substitutions:
  _REPO: jobs
  _IMAGE_NAME: product-determination
  _TAG: "251121"

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - backend/jobs/product_determination/Dockerfile
      - -t
      - asia-northeast1-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_IMAGE_NAME}:${_TAG}
      - .

images:
  - asia-northeast1-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_IMAGE_NAME}:${_TAG}
