"""Utility helpers for generating TikTok request signatures using tiktok-signature."""

from functools import lru_cache
from typing import Optional

from tiktok_signature import TikTokSignature

from .exceptions import SignatureGenerationError


@lru_cache(maxsize=1)
def _get_signer(user_agent: str) -> TikTokSignature:
    try:
        return TikTokSignature(user_agent=user_agent)
    except Exception as exc:  # noqa: BLE001
        raise SignatureGenerationError("TikTokSignature の初期化に失敗しました") from exc


def generate_x_bogus(url: str, user_agent: str, *, payload: Optional[str] = None) -> str:
    """Generate X-Bogus signature for the given URL and payload.

    Parameters
    ----------
    url: str
        The full request URL (without the X-Bogus query parameter).
    user_agent: str
        The UA string that will be used for the request.
    payload: Optional[str]
        Optional request body. Some endpoints include POST data in the signature calculation.

    Returns
    -------
    str
        The X-Bogus signature generated by tiktok-signature.
    """

    if not url or not user_agent:
        raise SignatureGenerationError("url と user_agent は必須です")

    signer = _get_signer(user_agent)
    try:
        return signer.get_x_bogus(url, payload or "")
    except Exception as exc:  # noqa: BLE001
        raise SignatureGenerationError("X-Bogus の生成に失敗しました") from exc
