apiVersion: v1
kind: Service
metadata:
  name: video-crawler-service
  namespace: crawlers
spec:
  selector:
    app: video-crawler
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer 