apiVersion: skaffold/v2beta29
kind: Config
build:
  artifacts:
  - image: tiktok-analytics-api
    docker:
      dockerfile: Dockerfile
  local:
    push: false
    useDockerCLI: true
deploy:
  kubectl:
    manifests:
    - service.yaml
  kubeContext: cloud-run-dev-internal